avatar: /img/avatar.png
background:
    path: /img/banner.png
    width: 1200
    height: 500
favicon:
  href: /favicon.ico # 网站图标
  type: image/x-icon # 图标类型，可能的值有(image/png, image/vnd.microsoft.icon, image/x-icon, image/gif)

function: # 功能开关，可选值（true,false）
  globalToc: true # 开启该功能会自动开启文章 TOC（文章目录） 功能
  wordCount: false # 是否开启文章字数统计 (true, false)
  copyCode: true # 是否允许复制代码块

imageCDN: # 图片 CDN 功能
  enable: false # 开启该功能  
  origin: /../../images/ # 图片原始目录
  to: https://cdn.jsdelivr.net/gh/nexmoe/nexmoe.github.io@latest/images/ # 图片 CDN 域名

  
# 附加图标库 使用说明：https://docs.nexmoe.com/config/icon
iconlib: # //at.alicdn.com/t/font_1038733_0xvrvpg9c0r.css


widgets:
    - name: social
      enable: true
      options: 
        social:
            GitHub:
                - https://github.com/kamadoori/
                - icon-github
                - rgb(200, 200, 200)
                - rgba(200, 200, 200, .1)
    - name: category
      enable: true
    - name: archive #settings: widgetAchive
      enable: true
      options:
        widgetAchive: #文章归档组件
            archive_type: 'year' #按月展示还是按年展示
            show_count: true  #是否展示数量
    - name: recent_posts
      enable: true

slotHead: | 
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-4D4ZJ9G024"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag("js", new Date());

    gtag("config", "G-4D4ZJ9G024");
  </script>
